# for use with conda (https://github.com/conda-forge/miniforge):
# conda env create -f environment.yml
name: "opzioni"
dependencies:
  - gxx=15
  - clang-tools=21
  - make
  - meson=1.7
  - ninja=1.12
